### ISSUE TITLE
Two icons for hue dimmer

### ISSUE THREAD

**Issue by papagei1996** [ioBroker/ioBroker.mobile#19]
When I insert a dimmer button for a hue lamp it will show one big and one small light bulb over each other 
![image](https://user-images.githubusercontent.com/56414714/67148154-74ce2e00-f29c-11e9-9a0f-498dff1f0097.jpg)

**Comment by Apollon77** [comment]
This is "as designed" and mobile is not developed further, so it will also stay that way

**Comment by papagei1996** [comment]
Is there an anything like mobile what I can use?


Von meinem iPhone gesendet

**Comment by Apollon77** [comment]
Check out material, iqontrol, habpanel, lovelace, tileboard ... all visu adapters ...
