### ISSUE TITLE
[Feature request] Browsernotifications

### ISSUE THREAD

**Issue by Xyolyp** [ioBroker/ioBroker.mobile#5]
I would love to see an object endpoint (or to be exact two to three grouped together) which enables the adapter to push browser notifications to the devices which subscribed to the notifications. The data I would like to be able to provide for the notification in the first implementation would be the title and a description. Maybe it's later possible to add buttons which perform some actions in ioBroker, change the image or maybe even send an image as the description. It would be nice to add a timeout option for the notification and/or a way to remove a notification after publishing it but these things can wait for iteration two.

**Comment by GermanBluefox** [comment]
I stopped the development of mobile. All request should be done in iobroker.material.
