### ISSUE TITLE
Zustände verdreht bei Jalousie

### ISSUE THREAD

**Issue by meicker** [ioBroker/ioBroker.mobile#6]
Jalousie ist mit 100% offen und 0% geschlossen. Kann man einen Schalter in die Optionen bauen der diese Logik umdreht ?

**Comment by Apollon77** [comment]
Mobile wird nicht aktiv weiterentwickelt. 

Material ist die nächste Stufe

**Comment by meicker** [comment]
Hallo 😁

vielen Dank für die Info 👍 Wo finde ich Material denn ? Als Adapter (noch) nicht verfügbar ?

Viele Grüsse,
Marc

**Comment by Apollon77** [comment]
Doch im Latest-Repo. --> https://forum.iobroker.net/viewtopic.php?f=20&t=15451

**Comment by meicker** [comment]
Danke für den Link :-)

Leider bin ich noch recht frisch dabei …

npm sagt mir schon was - aber wie auf latest repro stellen ? Habe ich zumindest im Forum so gelesen … 

Was muss ich machen um das Ding zu installieren :-)

Viele Grüße,
Marc

**Comment by Apollon77** [comment]
IoBroker Einstellungen - verwahrungsort ...

**Comment by meicker** [comment]
OK :-) Da steht ‚latest‘ drin - aber wie gehe ich nun mit dieser Info um ? Ich finde das nächste easter egg nicht … :-)

Viele Grüße,
Marc

**Comment by meicker** [comment]
HABS :-) !!!!!! :-) ALLES GUT !

Viele Grüße,
Marc
