### ISSUE TITLE
Bezeichnungen aus Aufzählungen fehlerhaft

### ISSUE THREAD

**Issue by davincino** [ioBroker/ioBroker.mobile#7]
Hallo,

für eine schnelle Umsetzung der mobilen Visualisierung setze ich diesen Adapter ein. Allerdings werden sowohl die Hauptgruppen (z.B. Räume und Funktionen) als auch die Untergruppen (z.B. Wohnzimmer, Küche usw.) nicht automatisch übernommen. Es werden immer die neuen Felder erstellt, aber überall steht [object Object] drin. Manuelle Bearbeitung ist möglich und funktioniert auch.
Habe die aktuellsten Adapter, da ioBroker frisch installiert ist. Evtl. müsste nur eine Kleinigkeit angepasst werden. 
Dass früher die automatische Benennung funktioniert hat, weiß ich nur weil ich es in einem Tutorial Video gesehen hatte. 

Danke + Gruß, Giuseppe

**Comment by Apollon77** [comment]
mobile Adapter ist "end of life" ... bitte material nutzen
